### PR TITLE
Update manifest.json

### PR DESCRIPTION
**Pull request by Alireza01**
:)

### CODE REVIEW

**Comment by Dziango** [comment]
Hey there, 2 questions:
1. Why changing "content_script"'s "matches" value?
2. Why removing "activeTab" permission? Is it not necessary nowadays?

**Comment by Alireza01** [comment]
1. actually i think your content_scripts are better but i think twitch.tv is enough 
2. The codes work without this permission on all the browsers

**Comment by Dziango** [comment]
1. U might be right. I'm not sure why I've put these .ttvnw.net and .twitchcdn.net there. Propably someone requsted that. In the end leaving that there doesn't hurt. Up to you :)
2. Were you able to confirm that your code does indeed work on firefox when the permission is granted? If that is the case then I see no reason not to merge your changes and upload them to chrome/ff stores :)

**Comment by alirezaabdi01** [comment]
Here is a problem:
with or without activeTab permission, Still i need to confirm extention to access twitch website data:
https://i.ibb.co/bgTT1FG/Screenshot-2023-05-21-180336.png

**Comment by alirezaabdi01** [comment]
How about test it on chrome store for now then we will think for ff

**Comment by alirezaabdi01** [comment]
this is the manifest should be used for ff:
{
  "name": "My Test",
  "description": "My Test",
  "version": "0.2",
  "manifest_version": 2,
  "content_scripts": [
    {
      "matches": ["*://www.twitch.tv/*"],
      "run_at": "document_end",
      "js": ["injected.js"]
    }
  ],
  "icons": {
    "32": "32.png",
    "48": "48.png",
    "64": "64.png"
  },
  "web_accessible_resources": ["injected.js"]
}

**Comment by Alireza01** [comment]
Here is the last edit and it works fine with edge and chrome and ff
and also I changed manifest version to 2 but chrome and edge will not support manifest v2 for 2024 and later

**Comment by Dziango** [comment]
So, if I understand you correctly, manifest version was reverted back to v2 in order for the extension to work properly on firefox and, at the same time, chrome and edge will stop supporting it by the end of the year. Is that correct?
Do you know why the extension doesn't work on firefox with manifest v2?

**Comment by Alireza01** [comment]
The codes don't work on ff with manifest v3 because they are adopting v3:

https://blog.mozilla.org/addons/2022/05/18/manifest-v3-in-firefox-recap-next-steps/

https://github.com/w3c/webextensions/issues/134

The codes easily work on chrome and edge with putting manifest version on 3 but for ff we need some codes. The problem is that ff doesn't give permissions automatically anymore to the extensions. So i will test to see if i can request permission on install.

**Comment by Alireza01** [comment]
I think for now we can put manifest version on 3 for chrome and put manifest version on 2 for ff and see when will ff stop supporting manifest v2
ff is really making everything hard in v3
Although it's not a big deal if we put the manifest version on 3 for ff but user should be smart enough to read our description and active this: 
image

**Comment by Alireza01** [comment]
I researched and it looks like ff's manifest v3 will get completed in September 2023.
So let's publish the codes on chrome with manifest v3 and on ff with manifest v2.
And after ff completed their manifest v3, we will change the codes.

**Comment by Dziango** [comment]
@alirezaabdi01 what do you say we simply go for a manifest v3 straight away? It needs to be done sooner or later anyway, so why not right now.
I'll make sure to edit extension's description in firefox store and include info about permissions.

**Comment by Alireza01** [comment]
The thing is it's akward to tell people to go there, and go there, and active this, do this, do that ....
We have 6 months until 2024 so we can hold to v2 for at least 5 months then surely firefox will finish and publish their v3 in October and we can change the codes to v3 and make the permission process automate or at least much easier like requesting permission on twitch website.
For example I researched for requesting permission on v3 and it's still not ready.
Did you test the codes?
Edit: It's not necessary to put different versions for chrome and ff. V2 is good for both of them for 5 months.

**Comment by Dziango** [comment]
@alirezaabdi01 Okay, I hear you. Let's do it your way then. We just got to remember about that issue in 5 months :)
Yea, I tested it on Chrome and Firefox and it seems to work correctly.
I've submitted and update for review in both Chrome Web Store and Firefox Add-ons. It may take few days (up to 1 month!) before it's accepted and published.
I'll let you know when that happens :)

**Pull request merged**
